### ISSUE TITLE
The base cannot start.

### ISSUE THREAD

**Issue by zisis912** [RayzrDev/bot-base#2]
when I try to start bot.js, i get this error. always. Other bases work, like a 10 line base another user gave me. Here is the error, hope you can help me
![image](https://user-images.githubusercontent.com/65046191/99786892-b37d8a00-2b27-11eb-9369-a0edc597e03d.png)

**Comment by foxfirecodes** [comment]
please read the README for instructions on setting up and running the bot. you're using the wrong command in the wrong folder.
